#!/usr/bin/env bash
#
#  888d888 .d8888b
#  888P"  d88P"
#  888    888
#  888    Y88b.
#  888     "Y8888P
#
# -------------------------------------------------------------------------
# Version: 0.1
# File: rc
# Source: https://github.com/devpunks
# Author: Ahmid-Ra (github.com/snuggs)
# Maintainer: devPunks <https://github.com/devpunks>
# Description: SSH Run Commands (rc)
# -------------------------------------------------------------------------

echo 'devPunks Local SSH .rc (Run Commands)'
