#!/bin/bash

SESSION=`whoami`

# Setup a work space called `$SESSION
# first window has 1 pane.
# Pane #1 -  split vertically 70%, set to root and running vim

# start server
tmux start-server

# create new session
tmux new-session -d -s $session -n "🕶️ devPunks"

# Select pane 0 run vim
tmux select-pane -t 0
tmux send-keys "vim" C-m

# Split pane 1 vertically by 30%
tmux split-window -h -l 30
tmux send-keys "git status" C-m

# Split pane 1 horizontally
tmux split-window -v -l 5 -c "$(pwd)"

# Select pane 0
tmux select-pane -t 0

# Split pane 1 horizontally
tmux split-window -v -l 1
tmux send-keys "clear && pwd" C-m

# Select pane 2
tmux select-pane -t 3

# attach to new session
tmux -2 attach -t $session
