#!/bin/bash

# https://gist.github.com/sdondley/b01cc5bb1169c8c83401e438a652b84e
# `split-window` fullscreen - https://unix.stackexchange.com/questions/124310

USER=`whoami`
SESSION='devPunks😈studio'
SOCKET='devpunks' # See tmux -L|S <socket|file> flag

# start server
tmux start-server

# Setup a session work space called `$SESSION
tmux new-session -AdP -s $SESSION -n "Vi" -x $COLUMNS -y $LINES

# attach to new session
tmux -v -u2 attach

tmux send-keys 'vi' C-m

# Split pane 0 vertically by 30%
tmux split-window -h -l 30
tmux send-keys "git status" Enter

# Split pane 1 horizontally
tmux split-window -v -l 5
tmux send-keys "pwd" Enter

# Select pane 0
tmux select-pane -t 0

# Split pane 0 horizontally
tmux split-window -v -l 1
tmux send-keys "clear" Enter
