#!/bin/bash

# https://gist.github.com/sdondley/b01cc5bb1169c8c83401e438a652b84e
# fullscreen split - https://unix.stackexchange.com/questions/124310

# Use PIPES for race conditions in pane creation commands
#   - https://www.manniwood.com/2021_08_02/fun_with_tmux.html
DELAY=0.5
SESSION='devPunks😈studio'
SOCKET='devpunks' # See tmux -L|S <socket|file> flag

echo COLUMNS $COLUMNS
echo LINES $LINES

# Setup a session work space called `$SESSION
tmux new-session -d -s $SESSION -x - -y -

# Split pane vertically by 30%
tmux split-window -h -l 40%
sleep $DELAY
tmux send-keys 'git status' Enter

# Split pane 1 horizontally
tmux split-window -v -l 30%
sleep $DELAY
tmux send-keys 'pwd' Enter

# Split first pane horizontally
tmux select-pane -t 1
tmux split-window -t 1 -v -l 20%
sleep $DELAY
tmux send-keys 'clear' Enter

tmux select-pane -t 1
sleep $DELAY
tmux send-keys 'vi' Enter

# Split pane 0 horizontally
# tmux split-window -v -l 1
# umux send-keys 'clear' Enter
