#!/bin/bash

########################################################
# TERMUX - https://wiki.termux.com/wiki/Postgresql

# PostgreSQL 16.x - https://www.postgresql.org/about/news/postgresql-16-released-2715/
declare -xr PGVERSION=15

########################################################


declare -xr FIXPRE=${PREFIX:-/shazaam}

# declare -xr PGBIN=/usr/local/Cellar/postgresql@${PGVERSION}/${PGVERSION}.0_1/bin
declare -xr PGBIN=${FIXPRE}/bin
declare -xr EXEC=${PGBIN}/pg
declare -xr COMMAND=$1
declare -xr OPERATION=$2
declare -xr LOG=`pwd`/PG.log
declare -xr AUTH=--auth-local # --auth-host
declare -xr USERNAME=devpunks
declare -xr HOST=localhost
declare -xr PORT=5432
# declare -xr PID=${PGDATA}/postmaster.pid

function status {
  ${EXEC}_ctl status --pgdata=$PGDATA
}

echo FIXPRE 👉 $FIXPRE
echo PGVERSION 👉 $PGVERSION
echo PGDATA 👉 $PGDATA
echo EXEC 👉 $EXEC
echo LOG 👉 $LOG
echo AUTH 👉 $AUTH
echo COMMAND 👉 $COMMAND

status

exit 0

# REMOVE ME!
# pg_ctl stop -D $PGDATA -l $LOG -s -m fast
# ls $PGDATA
# rm -rf $PGDATA
# pg_ctl init -D $PGDATA -l $LOG


# Run ls -al /usr/local/bin | grep pg_ for Postgres commands
# pg_dump[all]
# pg_verifybackup
# pg_upgrade
# pg_restore
# pg_isready


status

${EXEC}_${COMMAND} ${OPERATION} --pgdata=$PGDATA --log=$LOG -s -m fast
#pg_ctl -l $LOG -D $PGDATA $COMMAND -s -m fast

status
