#!/bin/bash

########################################################
# TERMUX - https://wiki.termux.com/wiki/Postgresql
#
# https://thenewstack.io/a-cheat-sheet-to-database-access-control-postgresql

########################################################

# Debian /usr
# Darwin /usr/local
# MacOS >M1 /opt/homebrew
# Termux /data/data/com.termux/files/usr
declare -xr PREFIX=${PREFIX:-/usr/}
declare -xr LOGDIR=${LOGDIR:-$PREFIX/var/log}

declare -xr PGBIN=${PREFIX}/bin
declare -xr EXEC=${PGBIN}/pg_

# Darwin / MacOS >M1 $PREFIX/var/postgres
# Debian / Termux $PREFIX/var/lib/pgsql/data
declare -xr PGDATA=${PGDATA:-$PREFIX/var/lib/pgsql/data}
declare -xr COMMAND=$1
declare -xr OPERATION=$2
declare -xr PORT=5432
declare -xr HOST=localhost
declare -xr USERNAME=devpunks
declare -xr AUTH=--auth-local # --auth-host
# declare -xr PID=${PGDATA}/postmaster.pid

# function status {
#   ${EXEC}ctl status --pgdata=$PGDATA
# }

echo FIXPRE 👉 $FIXPRE
echo PGVERSION 👉 $PGVERSION
echo PGDATA 👉 $PGDATA
echo EXEC 👉 $EXEC
echo LOGDIR 👉 $LOGDIR
echo PORT 👉 $PORT
echo AUTH 👉 $AUTH
echo COMMAND 👉 $COMMAND

status

exit 0

# REMOVE ME!
# pg_ctl stop -D $PGDATA -l $LOGDIR -s -m fast
# ls $PGDATA
# rm -rf $PGDATA
# pg_ctl init -D $PGDATA -l $LOGDIR


# Run ls -al /usr/local/bin | grep pg_ for Postgres commands
# pg_dump[all]
# pg_verifybackup
# pg_upgrade
# pg_restore
# pg_isready


status

${EXEC}_${COMMAND} ${OPERATION} --pgdata=$PGDATA --log=$LOGDIR -s -m fast
#pg_ctl -l $LOGDIR -D $PGDATA $COMMAND -s -m fast

status
